name: audit

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit_ci:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup audit-ci
        run: npm install -g audit-ci

      - name: Audit NPM Infra dependencies
        run: audit-ci --medium

      - name: Audit NPM App dependencies
        run: cd lib/admin && audit-ci --medium
